Product.LocalizedName = "Window Debugger"
App.UI.SearchWatermark = "Search"
App.UI.SettingsButton = "Settings"
App.UI.AboutButton = "Settings"
App.UI.ReloadButton.Content = "Reload"
App.UI.ReloadButton.ToolTip.Title = "Reload"
App.UI.ReloadButton.ToolTip.Description = "Reload the window list."
App.UI.CaptureButton.Content = "Capture"
App.UI.CaptureButton.ToolTip.Title = "Capture Window"
App.UI.CaptureButton.ToolTip.Description = "After clicking this button, the next window you click with the mouse will be captured and selected in this list."
App.UI.TopmostButton.Content = "Topmost"
App.UI.TopmostButton.ToolTip.Title = "Topmost"
App.UI.TopmostButton.ToolTip.Description = "Toggle the topmost state of the window."
App.UI.UacButton.Content = "UAC"
App.UI.UacButton.ToolTip.Title = "Restart as Administrator"
App.UI.UacButton.ToolTip.Description = "Restart this program with administrator privileges so that you can view and modify information of high privilege windows."
App.UI.Filter.DefaultFilter = "Visible Top-Level"
App.UI.Filter.FilterTitle = "Including these windows"
App.UI.Filter.FilterDescription = "By default, only visible top-level windows are shown in the list. Check to show more windows."
App.UI.Filter.IncludingInvisibleWindow = "Invisible Window"
App.UI.Filter.IncludingEmptyTitleWindow = "Empty Title Window"
App.UI.Filter.IncludingChildWindow = "Child Window"
App.UI.Filter.IncludingMessageOnlyWindow = "Message-Only Window"
App.UI.Filter.DefaultGroup = "Process/Window"
App.UI.Filter.GroupTitle = "Group by"
App.UI.Filter.GroupByProcessTopLevelChild = "Process / Top-Level Window / Child Window"
App.UI.Filter.GroupByTopLevelChild = "Top-Level Window / Child Window"
App.UI.Filter.GroupByProcessWindow = "Process / Window"
App.UI.Filter.NoGroup = "None (Flatten Window List)"
App.UI.Filter.DefaultSearch = "Search"
App.UI.Filter.SearchTitle = "Search"
App.UI.Filter.SearchIncludingHwnd = "HWND (Exact Match)"
App.UI.Filter.SearchIncludingXid = "XID (Exact Match)"
App.UI.Filter.SearchIncludingTitle = "Window Title"
App.UI.Filter.SearchIncludingProcessName = "Process Name"
App.UI.Filter.DefaultSort = "Sort: None"
App.UI.Filter.SortTitle = "Sort"
App.UI.Filter.NoSort = "None"
App.UI.Filter.SortByHwnd = "Sort by HWND"
App.UI.Filter.SortByXid = "Sort by XID"
App.UI.Filter.SortByTitle = "Sort by Window Title"
App.UI.WindowDetail.EmptyWindowName = "Empty Title"
App.UI.WindowDetail.ReloadButton.Content = "Reload Window Info"
App.UI.WindowDetail.ReloadButton.ToolTip.Title = "Reload Window Info"
App.UI.WindowDetail.ReloadButton.ToolTip.Description = "Reload all information of this window and display it on the interface."
App.UI.WindowDetail.OpenDirectory.Content = "Reveal in File Manager"
App.UI.WindowDetail.OpenDirectory.ToolTip.Title = "Reveal in File Manager"
App.UI.WindowDetail.OpenDirectory.ToolTip.Description = "View this program in the default file manager."
App.UI.WindowDetail.ChangeButton = "Change"
App.UI.WindowDetail.Pages.Windows.Info.Title = "Info"
App.UI.WindowDetail.Pages.Windows.Info.WindowHandle = "Handle"
App.UI.WindowDetail.Pages.Windows.Info.ProcessName = "Process Name"
App.UI.WindowDetail.Pages.Windows.Info.ProcessId = "Process Id"
App.UI.WindowDetail.Pages.Windows.Info.ThreadId = "Thread Id"
App.UI.WindowDetail.Pages.Windows.Info.ClassName = "Class Name"
App.UI.WindowDetail.Pages.Windows.Info.DpiAwareness = "DPI Awareness"
App.UI.WindowDetail.Pages.Windows.Info.Dpi = "DPI"
App.UI.WindowDetail.Pages.Windows.Info.WindowTitle = "Text"
App.UI.WindowDetail.Pages.Windows.Info.Bounds.Title = "Rect"
App.UI.WindowDetail.Pages.Windows.Info.Bounds.Description = "Screen coordinates"
App.UI.WindowDetail.Pages.Windows.Info.Bounds.Left = "Left"
App.UI.WindowDetail.Pages.Windows.Info.Bounds.Top = "Top"
App.UI.WindowDetail.Pages.Windows.Info.Bounds.Width = "Width"
App.UI.WindowDetail.Pages.Windows.Info.Bounds.Height = "Height"
App.UI.WindowDetail.Pages.Windows.Info.WindowShowStates = "Show States"
App.UI.WindowDetail.Pages.Windows.Info.WindowDisplayAffinity = "Display Affinity"
App.UI.WindowDetail.Pages.Windows.Info.ParentWindowHandle = "Parent Window"
App.UI.WindowDetail.Pages.Windows.Info.OwnerWindowHandle = "Owner Window"
App.UI.WindowDetail.Pages.Windows.Styles.Title = "Styles"
App.UI.WindowDetail.Pages.Windows.Styles.FullTitle = "Window Styles"
App.UI.WindowDetail.Pages.Windows.Styles.DocumentLink = "https://learn.microsoft.com/en-us/windows/win32/winmsg/window-styles"
App.UI.WindowDetail.Pages.Windows.StyleExes.Title = "StyleExes"
App.UI.WindowDetail.Pages.Windows.StyleExes.FullTitle = "Extended Window Styles"
App.UI.WindowDetail.Pages.Windows.StyleExes.DocumentLink = "https://learn.microsoft.com/en-us/windows/win32/winmsg/extended-window-styles"
App.UI.WindowDetail.Pages.Windows.ClassStyles.Title = "ClassStyles"
App.UI.WindowDetail.Pages.Windows.ClassStyles.FullTitle = "Window Class Styles"
App.UI.WindowDetail.Pages.Windows.ClassStyles.DocumentLink = "https://learn.microsoft.com/en-us/windows/win32/winmsg/window-class-styles"
App.UI.WindowDetail.Pages.Windows.Dwm.Title = "DWM"
App.UI.WindowDetail.Pages.Windows.Dwm.FullTitle = "Desktop Window Manager"
App.UI.WindowDetail.Pages.Windows.Dwm.DocumentLink = "https://learn.microsoft.com/en-us/windows/win32/api/dwmapi/ne-dwmapi-dwmwindowattribute"
App.UI.WindowDetail.Pages.Windows.Dwm.DwmIsCompositionEnabled.True = "System DWM is enabled, the following settings are available."
App.UI.WindowDetail.Pages.Windows.Dwm.DwmIsCompositionEnabled.False = "‚ùåSystem DWM is disabled, the following settings are not available."
App.UI.WindowDetail.Pages.Windows.Dwm.DWMWA_NCRENDERING_ENABLED = "Is non-client rendering enabled"
App.UI.WindowDetail.Pages.Windows.Dwm.DWMWA_CAPTION_BUTTON_BOUNDS = "Caption Button Bounds"
App.UI.WindowDetail.Pages.Windows.Dwm.DWMWA_EXTENDED_FRAME_BOUNDS = "Extended Frame Bounds"
App.UI.WindowDetail.Pages.Windows.Dwm.DWMWA_CLOAKED = "Cloaked"
App.UI.WindowDetail.Pages.Windows.Dwm.DWMWA_NCRENDERING_POLICY = "Non-Client Rendering Policy"
App.UI.WindowDetail.Pages.Windows.Dwm.DWMWA_TRANSITIONS_FORCEDISABLED = "Is DWM TransitionsEnabled"
App.UI.WindowDetail.Pages.Windows.Dwm.DWMWA_NONCLIENT_RTL_LAYOUT = "Is Non-Client Area Content Right-To-Left Layout"
App.UI.WindowDetail.Pages.Windows.Dwm.DWMWA_FORCE_ICONIC_REPRESENTATION = "Is Force Iconic Representation"
App.UI.WindowDetail.Pages.Windows.Dwm.DWMWA_FLIP3D_POLICY = "Flip3D Policy"
App.UI.WindowDetail.Pages.Windows.Dwm.DWMWA_HAS_ICONIC_BITMAP = "Has Iconic Bitmap"
App.UI.WindowDetail.Pages.Windows.Dwm.DWMWA_DISALLOW_PEEK = "Is Disallow Peek"
App.UI.WindowDetail.Pages.Windows.Dwm.DWMWA_EXCLUDED_FROM_PEEK = "Is Excluded From Peek"
App.UI.WindowDetail.Pages.Windows.Dwm.DWMWA_CLOAK = "Is Cloak"
App.UI.WindowDetail.Pages.Windows.Dwm.DWMWA_FREEZE_REPRESENTATION = "Is Freeze Representation"
App.UI.WindowDetail.Pages.Windows.Operations.Title = "Operations"
App.UI.WindowDetail.Pages.Windows.Operations.WindowOperation.Title = "Window Common Operations"
App.UI.WindowDetail.Pages.Windows.Operations.WindowOperation.Description = "Call Win32 API to perform common operations on the window."
App.UI.WindowDetail.Pages.Windows.Operations.WindowOperation.SetForeground.Description = "Call the SetForegroundWindow function to bring the thread that created the specified window to the foreground and activate the window."
App.UI.WindowDetail.Pages.Windows.Operations.WindowOperation.SetForeground.Action = "Activate Window"
App.UI.WindowDetail.Pages.Windows.Operations.WindowOperation.Close.Description = "Trigger the WM_CLOSE message to close the window."
App.UI.WindowDetail.Pages.Windows.Operations.WindowOperation.Close.Action = "Close Window"
App.UI.WindowDetail.Pages.Windows.Operations.WindowInteractions.Title = "Window Other Operations"
App.UI.WindowDetail.Pages.Windows.Operations.WindowInteractions.Description = "Call Win32 API to perform other operations on the window."
App.UI.WindowDetail.Pages.Windows.Operations.WindowInteractions.RedrawWindow.Description = "Call the RedrawWindow function to update all areas in the window's work area."
App.UI.WindowDetail.Pages.Windows.Operations.WindowInteractions.RedrawWindow.Action = "Update Window"
App.UI.WindowDetail.Pages.Windows.Operations.WindowInteractions.FlashWindow.Description = "Call Flash Window to flash the specified window once. It does not change the active state of the window."
App.UI.WindowDetail.Pages.Windows.Operations.WindowInteractions.FlashWindow.Action = "Flash Window"
App.UI.WindowDetail.Pages.Windows.Operations.ProcessOperations.Title = "Process Operations"
App.UI.WindowDetail.Pages.Windows.Operations.ProcessOperations.Description = "Operate the process where the window is located."
App.UI.WindowDetail.Pages.Windows.Operations.ProcessOperations.Kill.Description = "Call the TerminateProcess function to terminate the process where this window is located and all its threads."
App.UI.WindowDetail.Pages.Windows.Operations.ProcessOperations.Kill.Action = "End Process"
App.UI.WindowDetail.Pages.Windows.Operations.ProcessOperations.ForceKill.Description = "Call the CreateRemoteThread function to run a thread in the virtual address space of the process where this window is located, and then call the CloseHandle function to close the process handle."
App.UI.WindowDetail.Pages.Windows.Operations.ProcessOperations.ForceKill.Action = "Force Kill Process"
App.UI.WindowDetail.Pages.Windows.Operations.ThreadOperations.Title = "Thread Operations"
App.UI.WindowDetail.Pages.Windows.Operations.ThreadOperations.Description = "Operate the thread where the window is located."
App.UI.WindowDetail.Pages.Windows.Operations.ThreadOperations.Suspend.Description = "Call the SuspendThread function to suspend the thread where the window is located."
App.UI.WindowDetail.Pages.Windows.Operations.ThreadOperations.Suspend.Action = "Suspend Thread"
App.UI.WindowDetail.Pages.Windows.Operations.ThreadOperations.Resume.Description = "Call the ResumeThread function to decrement the suspend count of the thread. When the suspend count is zero, the thread will resume execution."
App.UI.WindowDetail.Pages.Windows.Operations.ThreadOperations.Resume.Action = "Resume Thread"
App.UI.WindowDetail.Pages.Windows.Operations.ThreadOperations.Kill.Description = "Call the TerminateThread function to terminate the thread."
App.UI.WindowDetail.Pages.Windows.Operations.ThreadOperations.Kill.Action = "End Thread"
App.UI.WindowDetail.Pages.Windows.Others.Title = "Others"
App.UI.WindowDetail.Pages.Windows.Others.IsTouchWindow = "Is Touch Window"
App.UI.WindowDetail.Pages.Windows.Others.VirtualDesktopId = "Virtual Desktop ID"
App.UI.WindowDetail.Pages.Linux.Info.Title = "Info"
App.UI.WindowDetail.Pages.Linux.Properties.Title = "Properties"
App.UI.WindowDetail.Pages.Linux.Operations.Title = "Operations"
Dynamic.EnumValues.DPI_AWARENESS.DPI_AWARENESS_INVALID = "Invalid DPI awareness"
Dynamic.EnumValues.DPI_AWARENESS.DPI_AWARENESS_UNAWARE = "DPI unaware"
Dynamic.EnumValues.DPI_AWARENESS.DPI_AWARENESS_SYSTEM_AWARE = "System DPI aware"
Dynamic.EnumValues.DPI_AWARENESS.DPI_AWARENESS_PER_MONITOR_AWARE = "Per monitor DPI aware"
